[package]
name = "boe_completo_pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
lopdf = "0.34.0"
reqwest = { version = "0.12.11", default-features = false, features = ["rustls-tls"] }
scraper = "0.22.0"
tokio = { version = "1.42.0", features = ["full"] }
